{{
    config(
         materialized='table'
    )
}} 

WITH currency_cte AS (

    SELECT Distinct CURRENCYCODE FROM CME_DATABASE.PUBLIC.METALS 
    UNION 
    SELECT Distinct CURRENCYCODE FROM CME_DATABASE.PUBLIC.COMMODITY_AGR
    UNION 
    SELECT Distinct CURRENCYCODE FROM CME_DATABASE.PUBLIC.EQUITY
    UNION 
    SELECT Distinct CURRENCYCODE FROM CME_DATABASE.PUBLIC.INTEREST_RATE 
    UNION 
    SELECT Distinct CURRENCYCODE FROM CME_DATABASE.PUBLIC.ENERGY 
    UNION 
    SELECT Distinct CURRENCYCODE FROM CME_DATABASE.PUBLIC.CURRENCY
)

SELECT
CURRENCYCODE

FROM
currency_cte