{{
    config(
         materialized='table'
    )
}}

WITH facts_cte AS (

    SELECT ASSET, CURRENCYCODE, SECURITYEXCHANGE, SECURITYTYPE, 
    LEVEL1ASKDISPLAYPRICE, LEVEL1ASKORDER, LEVEL1ASKPRICE, LEVEL1ASKQUANTITY,
    LEVEL1BIDDISPLAYPRICE, LEVEL1BIDORDER, LEVEL1BIDPRICE, LEVEL1BIDQUANTITY,
     {{ "TO_CHAR(timestamp '2023-10-26T06:11:15.492Z', 'YYYYMMDDHH')" }} as date_id
    FROM CME_DATABASE.PUBLIC.METALS

    UNION
    
    SELECT ASSET, CURRENCYCODE, SECURITYEXCHANGE, SECURITYTYPE,
     LEVEL1ASKDISPLAYPRICE, LEVEL1ASKORDER, LEVEL1ASKPRICE, LEVEL1ASKQUANTITY,
    LEVEL1BIDDISPLAYPRICE, LEVEL1BIDORDER, LEVEL1BIDPRICE, LEVEL1BIDQUANTITY,
     {{ "TO_CHAR(timestamp '2023-10-26T06:11:15.492Z', 'YYYYMMDDHH')" }} as date_id
    FROM CME_DATABASE.PUBLIC.ENERGY
 
    UNION
 
    SELECT ASSET, CURRENCYCODE, SECURITYEXCHANGE, SECURITYTYPE,
    LEVEL1ASKDISPLAYPRICE, LEVEL1ASKORDER, LEVEL1ASKPRICE, LEVEL1ASKQUANTITY,
    LEVEL1BIDDISPLAYPRICE, LEVEL1BIDORDER, LEVEL1BIDPRICE, LEVEL1BIDQUANTITY,
     {{ "TO_CHAR(timestamp '2023-10-26T06:11:15.492Z', 'YYYYMMDDHH')" }} as date_id
    FROM CME_DATABASE.PUBLIC.COMMODITY_AGR
    
    UNION
 
    SELECT ASSET, CURRENCYCODE, SECURITYEXCHANGE, SECURITYTYPE,
    LEVEL1ASKDISPLAYPRICE, LEVEL1ASKORDER, LEVEL1ASKPRICE, LEVEL1ASKQUANTITY,
    LEVEL1BIDDISPLAYPRICE, LEVEL1BIDORDER, LEVEL1BIDPRICE, LEVEL1BIDQUANTITY,
     {{ "TO_CHAR(timestamp '2023-10-26T06:11:15.492Z', 'YYYYMMDDHH')" }} as date_id
    FROM CME_DATABASE.PUBLIC.CURRENCY  
 
    UNION
 
    SELECT ASSET, CURRENCYCODE, SECURITYEXCHANGE, SECURITYTYPE,
     LEVEL1ASKDISPLAYPRICE, LEVEL1ASKORDER, LEVEL1ASKPRICE, LEVEL1ASKQUANTITY,
    LEVEL1BIDDISPLAYPRICE, LEVEL1BIDORDER, LEVEL1BIDPRICE, LEVEL1BIDQUANTITY,
     {{ "TO_CHAR(timestamp '2023-10-26T06:11:15.492Z', 'YYYYMMDDHH')" }} as date_id
    FROM CME_DATABASE.PUBLIC.INTEREST_RATE
 
    UNION
 
    SELECT ASSET, CURRENCYCODE, SECURITYEXCHANGE, SECURITYTYPE,
     LEVEL1ASKDISPLAYPRICE, LEVEL1ASKORDER, LEVEL1ASKPRICE, LEVEL1ASKQUANTITY,
    LEVEL1BIDDISPLAYPRICE, LEVEL1BIDORDER, LEVEL1BIDPRICE, LEVEL1BIDQUANTITY,
     {{ "TO_CHAR(timestamp '2023-10-26T06:11:15.492Z', 'YYYYMMDDHH')" }} as date_id
    FROM CME_DATABASE.PUBLIC.EQUITY  
    

)

SELECT * 
FROM 
facts_cte

