{{ config(
    materialized='table'
) }}

WITH product_cte AS (
    
        SELECT Distinct ASSET, UNDERLYINGPRODUCT FROM CME_DATABASE.PUBLIC.METALS 
        UNION
        SELECT Distinct ASSET, UNDERLYINGPRODUCT FROM CME_DATABASE.PUBLIC.COMMODITY_AGR
        UNION
        SELECT Distinct ASSET, UNDERLYINGPRODUCT FROM CME_DATABASE.PUBLIC.EQUITY
        UNION
        SELECT Distinct ASSET, UNDERLYINGPRODUCT FROM CME_DATABASE.PUBLIC.INTEREST_RATE 
        UNION
        SELECT Distinct ASSET, UNDERLYINGPRODUCT FROM CME_DATABASE.PUBLIC.ENERGY 
        UNION
        SELECT Distinct ASSET, UNDERLYINGPRODUCT FROM CME_DATABASE.PUBLIC.CURRENCY
    
)

SELECT ASSET, UNDERLYINGPRODUCT
FROM product_cte
